name: Android Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Menggunakan versi terbaru
        with:
          fetch-depth: 0  # Pastikan riwayat commit tersedia

      - name: Set Up JDK 17
        uses: actions/setup-java@v3  # Versi terbaru
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set Up Android SDK
        uses: android-actions/setup-android@v3  # Pastikan versi terbaru

      - name: Grant Execute Permission to Gradle
        run: chmod +x ./gradlew

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Verify APK Output
        run: ls -alh app/build/outputs/apk/debug/  # Memeriksa apakah APK berhasil dibuat

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3  # Menggunakan versi terbaru
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
