name: Android Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set Up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK dan Build Tools
        run: sdkmanager "platforms;android-34" "build-tools;34.0.0"

      - name: Install XML Validator
        run: sudo apt-get install -y libxml2-utils

      - name: Validate XML Files
        run: |
          for file in $(find app/src/main/res -name "*.xml"); do
            xmllint --noout "$file" || (echo "❌ Error in $file" && exit 1)
          done

      - name: Download OpenCV SDK
        run: |
          wget -O opencv-4.11.0-android-sdk.zip https://github.com/opencv/opencv/releases/download/4.11.0/opencv-4.11.0-android-sdk.zip
          unzip opencv-4.11.0-android-sdk.zip
          mv OpenCV-android-sdk/sdk opencv

      - name: Grant Execute Permission to Gradle
        run: chmod +x ./gradlew

      - name: Clean Gradle Cache
        run: ./gradlew clean

      - name: Refresh Gradle Dependencies
        run: ./gradlew --refresh-dependencies

      - name: Debug Dependencies
        run: ./gradlew app:dependencies --stacktrace

      - name: Debug Build APK
        run: ./gradlew assembleDebug --stacktrace --debug --info

      - name: Verify APK Output
        run: ls -alh app/build/outputs/apk/debug/

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
          
